version: '3.9'

services:
  vue_app:
    container_name: vue_app
    image: col_trends-front:1-0.0
    build: ./col_trends-front
    ports:
      - 9000:8080
    depends_on:
      - java_app
  java_app:
    container_name: java_app
    image: col_trends-back:1-0.0
    build: ./col_trends-back
    ports:
      - 8080:8080
    volumes:
      - ./col_trends-back:/col_trends-back
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - GOOGLE_APPLICATION_CREDENTIALS=col_trends-back/fellow-405319-6403997004e5.json
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      
